### ISSUE TITLE
Revision

### ISSUE THREAD

**Issue by blinfoldking** [zia123123/proclub#1]
you have a pretty clean code, but there are some inappropriate space or newline.
please read and follow a style guide for example you can follow the 
[Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)

unfortunately for your ide itself is not following to our criteria for CLI application which have to be a developer tools, please refer back to the [Programmer Handbook](https://drive.google.com/file/d/1acTzougpw4bWsUXMXaHig40LELEF0_A6/view)

**Comment by blinfoldking** [comment]
and please add a readme.md so others can read what your project means

**Comment by vayupranaditya** [comment]
Well just to make it clearer, not just spaces and newlines. He/she needs to follow the naming convention too.

**Comment by blinfoldking** [comment]
agree @vayupranaditya, i don't really know the naming convention of java tho. so please refer back the Google Java Style Guide

**Comment by vayupranaditya** [comment]
Yep! It's all clearly described there.
